# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/combat/player_combat_stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/combat/player_combat_stats.proto',
  package='pogoprotos.data.combat',
  syntax='proto3',
  serialized_pb=_b('\n0pogoprotos/data/combat/player_combat_stats.proto\x12\x16pogoprotos.data.combat\"V\n\x11PlayerCombatStats\x1a\x41\n\x1bPlayerCombatBadgeStatsProto\x12\x0f\n\x07num_won\x18\x01 \x01(\x05\x12\x11\n\tnum_total\x18\x02 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PLAYERCOMBATSTATS_PLAYERCOMBATBADGESTATSPROTO = _descriptor.Descriptor(
  name='PlayerCombatBadgeStatsProto',
  full_name='pogoprotos.data.combat.PlayerCombatStats.PlayerCombatBadgeStatsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_won', full_name='pogoprotos.data.combat.PlayerCombatStats.PlayerCombatBadgeStatsProto.num_won', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_total', full_name='pogoprotos.data.combat.PlayerCombatStats.PlayerCombatBadgeStatsProto.num_total', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=162,
)

_PLAYERCOMBATSTATS = _descriptor.Descriptor(
  name='PlayerCombatStats',
  full_name='pogoprotos.data.combat.PlayerCombatStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_PLAYERCOMBATSTATS_PLAYERCOMBATBADGESTATSPROTO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=162,
)

_PLAYERCOMBATSTATS_PLAYERCOMBATBADGESTATSPROTO.containing_type = _PLAYERCOMBATSTATS
DESCRIPTOR.message_types_by_name['PlayerCombatStats'] = _PLAYERCOMBATSTATS

PlayerCombatStats = _reflection.GeneratedProtocolMessageType('PlayerCombatStats', (_message.Message,), dict(

  PlayerCombatBadgeStatsProto = _reflection.GeneratedProtocolMessageType('PlayerCombatBadgeStatsProto', (_message.Message,), dict(
    DESCRIPTOR = _PLAYERCOMBATSTATS_PLAYERCOMBATBADGESTATSPROTO,
    __module__ = 'pogoprotos.data.combat.player_combat_stats_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.data.combat.PlayerCombatStats.PlayerCombatBadgeStatsProto)
    ))
  ,
  DESCRIPTOR = _PLAYERCOMBATSTATS,
  __module__ = 'pogoprotos.data.combat.player_combat_stats_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.combat.PlayerCombatStats)
  ))
_sym_db.RegisterMessage(PlayerCombatStats)
_sym_db.RegisterMessage(PlayerCombatStats.PlayerCombatBadgeStatsProto)


# @@protoc_insertion_point(module_scope)
